### PR TITLE
GO SDK, Sidecar client with URL configuration

### PR DESCRIPTION
**Pull request by hiteshjoshi**
Small change to bring the sidecar URL in the client configuration.

### CODE REVIEW

**Comment by bmizerany** [comment]
Thank you for your contribution. This is a welcome addition, however the tests will not pass because of additional plumbing needing some maintenance. It's bedtime for me, but I'll post a PR tomorrow.

Thank you again!

**Comment by hiteshjoshi** [comment]
I just couldn't find how to run tests on client. 

However, ```go test -count=1 -v ./...``` runs fine

**Comment by hiteshjoshi** [comment]
Also, can you guide me If I want to use Tier as a library, how do I go about it?

**Comment by bmizerany** [comment]
@hiteshjoshi I've posted #201 with all the plumbing fixes I described.

> I just couldn't find how to run tests on client.
> However, go test -count=1 -v ./... runs fine

It's not apparent, I know, but most API/client tests are skipped unless a STRIPE_API_KEY is set. I'll change the tests to fail if that env var is not set in a future PR.

> Also, can you guide me If I want to use Tier as a library? How do I go about it?

Are you asking how to "embed" tier into your Go binary to avoid running a sidecar? If so, the official answer is: This is only supported as an "experimental" ATM, but it is how `cmd/tier` works, so you can find how to embed tier that way :)

I recommend the `cmd/tier` approach instead of using the `control` package because the `control` package makes no API compatibility promises and is subject to change at any time, but the `tier.Client` will remain stable.

The code of interest can be found here:

https://github.com/tierrun/tier/blob/29c54e8fc1c7bad86b24d04e8860904ea191032d/cmd/tier/tier.go#L512-L523

I think it's reasonable for a future PR to land that makes that a little more accessible. Maybe `tc, err := tier.EmbededFromEnv()` which does that right thing using the envs the same way `cmd/tier` does.

**Comment by bmizerany** [comment]
I'm closing this out. Please ask any further questions or give any feedback in #201.

**Comment by hiteshjoshi** [comment]
Thank you so much @bmizerany

**Comment by hiteshjoshi** [comment]
Is there a way I can buy you a beer bud?

**Comment by bmizerany** [comment]
@hiteshjoshi No need, but I won't turn one down. :) Thank you so much for your PR and for kicking this fix off!

**Pull request closed without merging**
