### PR TITLE
cmd/tier: add title field to feature, and other PJ changes

### PR DESCRIPTION
**Pull request by bmizerany**
This commit changes PricingJSON in the following ways:

* Adds a title field to the feature object
* Moves the interval field up from feature to plan
* Moves the currency field up from feature to plan

The above changes were made to support a new plan name (for display)
format in Stripe. The new format is now:

  "PlanName (Interval): FeatureName (PlanVersion)"

In addition to the above change, this commit also contains a
rip-and-replace of the Stripe SDK with a much simpler recipe of the
standard http client, the json package, and a few helpers for building
Stripe form-encoded request payloads and retrieving lists of objects
back from stripe. This resulting in a significant reduction in the
codebase that dealt with Stripe and gives us a lot more flexibility and
power now, and in the future.

### CODE REVIEW

**Comment by isaacs** [comment]
Is the `tier.limit` metadata not getting set anymore?  I have a pricing.json like this:

```json
{
  "plans": {
    "plan:example@1": {
      "title": "Just an example plan to show off features",
      "interval": "@daily",
      "features": {
        "feature:daily": {
          "tiers": [
            {
              "base": 1,
              "upto": 10
            }
          ]
        }
      }
    }
  }
}
```

But on the product/price created, I don't see any `tier.limit` metadata.

Screen Shot 2022-09-21 at 12 19 03

**Comment by isaacs** [comment]
Also, it looks like the `tiers` information isn't making it up to Stripe.


```json
{
  "plans": {
    "plan:example@1": {
      "title": "Just an example plan to show off features",
      "features": {
        "feature:graduated": {
          "tiers": [
            {
              "upto": 10
            },
            {
              "upto": 20,
              "price": 100
            },
            {
              "price": 50
            }
          ],
          "mode": "graduated"
        }
      }
    }
  }
}
```

Screen Shot 2022-09-21 at 12 16 57

**Comment by bmizerany** [comment]
@isaacs What SHA did that happen at?

**Comment by bmizerany** [comment]
> Is the `tier.limit` metadata not getting set anymore? I have a pricing.json like this:
> 
> ```json
> {
>   "plans": {
>     "plan:example@1": {
>       "title": "Just an example plan to show off features",
>       "interval": "@daily",
>       "features": {
>         "feature:daily": {
>           "tiers": [
>             {
>               "base": 1,
>               "upto": 10
>             }
>           ]
>         }
>       }
>     }
>   }
> }
> ```
> 
> But on the product/price created, I don't see any `tier.limit` metadata.
> 

The metadata is now on the price.

CleanShot 2022-09-23 at 10 41 51@2x

**Comment by bmizerany** [comment]
> Also, it looks like the tiers information isn't making it up to Stripe.

It wasn't, but should be now. This is still a WIP branch and needed more testing. Tests are in place to help prevent this regression after the rip-and-replace of the Stripe SDK.

**Comment by isaacs** [comment]
That was on [9ecd77b](https://github.com/tierrun/tier/pull/66/commits/9ecd77bf525576436a799b82141a857f7acf4fb1)

Now on 4c023c2, I see it pushing the tiers and limit meta.

`tier pull` is returning raw golang style keys, rather than JSON, though:

```json
[
     {
          "ProviderID": "price_1LlG0EKajPHS2Vke1q77oWYZ",
          "Plan": "plan:example@1",
          "Name": "feature:daily",
          "Interval": "@daily",
          "Currency": "usd",
          "Title": "Just an example plan to show off features (daily) - feature:daily",
          "Base": 0,
          "Mode": "graduated",
          "Aggregate": "sum",
          "Tiers": [
               {
                    "Upto": 10,
                    "Price": 0,
                    "Base": 1
               }
          ]
     }
]
```

**Comment by bmizerany** [comment]
@isaacs Please help test `pull` when you have a minute. It should be working with only one caveat: `title` on plan and feature are a little weird because I'm not yet splitting them in an way that is easy to RoundTrip. I plan to use metadata to do this, and will take a stab at it soon.

How to test pull:

* push
* pull and note:
  * the title in stripe (if not set in PJ) should be the feature name (e.g. `feature:x`) but on pull it should be omitted in the output. The same goes for zero values of aggregate, interval, plan title, etc.

-b

**Comment by bmizerany** [comment]
Features may now have titles for use with building product titles per price in Stripe. The new title field is marshaled and unmarshaled on push and pull respectively. The "human" title is only seen in Stripe and not "settable" directly but is built using ids or titles, the interval, and the version if available.

```json
{
  "plans": {
    "plan:example@1000": {
      "title": "Just an example plan to show off features",
      "features": {
        "feature:graduated": {
	  "title": "xxxxxx",
          "tiers": [
            {
              "upto": 10
            },
            {
              "upto": 20,
              "price": 100
            },
            {
              "price": 50
            }
          ],
          "mode": "graduated"
        }
      }
    }
  }
}
```

CleanShot 2022-09-24 at 17 14 17@2x

**Pull request merged**
